### ISSUE TITLE
Problems with MathWallet Chrome extension

### ISSUE THREAD

**Issue by 4skinSkywalker** [mathwallet/MathChain#30]
Hi guys,
sorry if I picked the wrong repo to post this issue, but I didn't immediately found the MathWallet repo (Chrome extension).

A user of our app (Ethbox) is having troubles with getting the dapp working with MetaMask because of the following errors blocking the execution of the code.

![image](https://user-images.githubusercontent.com/17194393/131399594-ddd0368a-628e-4f86-8a5a-9f656c22d505.png)

The problem fixes as soon as he disables MathWallet.
What is going on and how to fix it my side (code) when a user with MathWallet visits the page?

Thanks

**Comment by hging** [comment]
Thanks for report.
I suggest your wallet is in Solana Mainnet Beta network.
So there is no eth environment injection to your dapp page.
I think you can change your network to Ethereum in our extension.
If you have any other issue. you can join our [discord](https://discord.gg/gXSfnk5eP5).
