### ISSUE TITLE
Mathwallet is the wallet like no other.

### ISSUE THREAD

**Issue by cryptoXscout** [mathwallet/MathChain#34]
Hello Math Wallet, team. How are you guys doing?
It's no surprise that backed by the biggest in the crypto space. 
You doing a fantastic job that is why I want to ask you - if you have any plans to integrate blockchain - ICON Foundation/ICX. 
I'm sure that you know the project and because of that and their growth - am looking for the possibilities to bring based o the interoperability ICX ecosystem, a wallet with full integration of ICE as EVM based on Substrate. 

Greetings

G.

**Comment by csiklyaistvan** [comment]
Ez jo

**Comment by Mrt3383x38** [comment]
Burda böyle izleyecekmiyiz

**Comment by Mrt3383x38** [comment]
Para cekilmiyo uygulama nasıl ilerlenecek biyardımcı olsanız

**Comment by Mrt3383x38** [comment]
> Hello Math Wallet, team. How are you guys doing?
> It's no surprise that backed by the biggest in the crypto space. 
> You doing a fantastic job that is why I want to ask you - if you have any plans to integrate blockchain - ICON Foundation/ICX. 
> I'm sure that you know the project and because of that and their growth - am looking for the possibilities to bring based o the interoperability ICX ecosystem, a wallet with full integration of ICE as EVM based on Substrate. 
> 
> Greetings
> 
> G.
>
